//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/j/j/o/jjose3/modulo/moduloadder/rtl/fourbitadder.vp
//  Source template: fourbitadder
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

// fourbitadder.vp


module fourbitadder (
         input  logic [3:0] a,
         input  logic [3:0] b,
         input  logic cin,
         output logic [3:0] s,
         output logic cout );

logic cout0, cout1, cout2; 

fulladder  FULLADDER0 ( .a(a[0]), .b(b[0]), .cin(cin), .s(s[0]), .cout(cout0) );

fulladder  FULLADDER1 ( .a(a[1]), .b(b[1]), .cin(cout0), .s(s[1]), .cout(cout1) );

fulladder  FULLADDER2 ( .a(a[2]), .b(b[2]), .cin(cout1), .s(s[2]), .cout(cout2) );

fulladder  FULLADDER3 ( .a(a[3]), .b(b[3]), .cin(cout2), .s(s[3]), .cout(cout) );


endmodule: fourbitadder
